version: "2"
networks:
  event-net:
    driver: bridge
    name: event-net
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - event-net

  kafka:
    image: bitnami/kafka:2.8.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      # KAFKA_BROKER_ID: 1
      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      # KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      # KAFKA_CFG_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper
    networks:
      - event-net
